-- Create EVENTS table for Calendar functionality
-- Schema: MSMM DASHBOARD

CREATE TABLE "MSMM DASHBOARD"."EVENTS" (
    EVENT_ID NUMBER(22) GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    TITLE VARCHAR2(800) NOT NULL,
    DESCRIPTION VARCHAR2(2400),
    START_DATE DATE NOT NULL,
    END_DATE DATE NOT NULL,
    LOCATION VARCHAR2(400),
    COLOR VARCHAR2(20) DEFAULT '#3B82F6',
    ALL_DAY VARCHAR2(1) DEFAULT 'N' CHECK (ALL_DAY IN ('Y', 'N')),
    CREATED_DATE DATE DEFAULT SYSDATE,
    MODIFIED_DATE DATE DEFAULT SYSDATE
);

-- Add comments for documentation
COMMENT ON TABLE "MSMM DASHBOARD"."EVENTS" IS 'Calendar events for Business Development tracking';
COMMENT ON COLUMN "MSMM DASHBOARD"."EVENTS".EVENT_ID IS 'Unique event identifier (auto-generated)';
COMMENT ON COLUMN "MSMM DASHBOARD"."EVENTS".TITLE IS 'Event title/name';
COMMENT ON COLUMN "MSMM DASHBOARD"."EVENTS".DESCRIPTION IS 'Event description or notes';
COMMENT ON COLUMN "MSMM DASHBOARD"."EVENTS".START_DATE IS 'Event start date/time';
COMMENT ON COLUMN "MSMM DASHBOARD"."EVENTS".END_DATE IS 'Event end date/time';
COMMENT ON COLUMN "MSMM DASHBOARD"."EVENTS".LOCATION IS 'Event location';
COMMENT ON COLUMN "MSMM DASHBOARD"."EVENTS".COLOR IS 'Event color code for calendar display';
COMMENT ON COLUMN "MSMM DASHBOARD"."EVENTS".ALL_DAY IS 'Y if all-day event, N otherwise';
COMMENT ON COLUMN "MSMM DASHBOARD"."EVENTS".CREATED_DATE IS 'Date record was created';
COMMENT ON COLUMN "MSMM DASHBOARD"."EVENTS".MODIFIED_DATE IS 'Date record was last modified';

-- Create indexes for performance
CREATE INDEX IDX_EVENTS_START_DATE ON "MSMM DASHBOARD"."EVENTS"(START_DATE);
CREATE INDEX IDX_EVENTS_END_DATE ON "MSMM DASHBOARD"."EVENTS"(END_DATE);

-- Create trigger to automatically update MODIFIED_DATE
CREATE OR REPLACE TRIGGER "MSMM DASHBOARD"."TRG_EVENTS_MODIFIED"
BEFORE UPDATE ON "MSMM DASHBOARD"."EVENTS"
FOR EACH ROW
BEGIN
    :NEW.MODIFIED_DATE := SYSDATE;
END;
/
